enableInlineBuilds: true

lockfileFilename: public-yarn.lock

nodeLinker: node-modules

npmAuthToken: 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

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
